//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEDASistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.ImparticionDeCursoes = new HashSet<ImparticionDeCurso>();
        }
    
        public int idCurso { get; set; }
        public string nombreCurso { get; set; }
        public Nullable<int> idModalidad { get; set; }
        public Nullable<System.TimeSpan> horas { get; set; }
        public Nullable<int> idSede { get; set; }
        public Nullable<int> idEstadoCursoPrograma { get; set; }
        public Nullable<int> idPrograma { get; set; }
    
        public virtual EstadoCursoPrograma EstadoCursoPrograma { get; set; }
        public virtual Modalidad Modalidad { get; set; }
        public virtual Programa Programa { get; set; }
        public virtual Sede Sede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImparticionDeCurso> ImparticionDeCursoes { get; set; }
    }
}
