//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEDASistema.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPIDEntities : DbContext
    {
        public BDPIDEntities()
            : base("name=BDPIDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Curso> Cursoes { get; set; }
        public virtual DbSet<Dependencia> Dependencias { get; set; }
        public virtual DbSet<EstadoCursoPrograma> EstadoCursoProgramas { get; set; }
        public virtual DbSet<EstadoParticipante> EstadoParticipantes { get; set; }
        public virtual DbSet<Facilitador> Facilitadors { get; set; }
        public virtual DbSet<Modalidad> Modalidads { get; set; }
        public virtual DbSet<Participante> Participantes { get; set; }
        public virtual DbSet<Programa> Programas { get; set; }
        public virtual DbSet<Sede> Sedes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipo> Tipoes { get; set; }
        public virtual DbSet<ImparticionDeCurso> ImparticionDeCursoes { get; set; }
    }
}
