//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEDASistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facilitador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facilitador()
        {
            this.ImparticionDeCursoes = new HashSet<ImparticionDeCurso>();
        }
    
        public int idFacilitador { get; set; }
        public long cedulaFacilitador { get; set; }
        public string contraseñaFacilitador { get; set; }
        public string nombreFacilitador { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string correoElectronico { get; set; }
        public long telefono { get; set; }
        public Nullable<int> idTipo { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImparticionDeCurso> ImparticionDeCursoes { get; set; }
    }
}
