//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEDASistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImparticionDeCurso
    {
        public Nullable<int> idFacilitador { get; set; }
        public Nullable<int> idParticipante { get; set; }
        public Nullable<int> idCurso { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFinal { get; set; }
        public Nullable<int> anno { get; set; }
        public Nullable<int> semestre { get; set; }
        public Nullable<float> nota { get; set; }
        public Nullable<int> idEstadoParticipante { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual EstadoParticipante EstadoParticipante { get; set; }
        public virtual Facilitador Facilitador { get; set; }
        public virtual Participante Participante { get; set; }
    }
}
