//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEDASistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programa()
        {
            this.Cursoes = new HashSet<Curso>();
        }
    
        public int idPrograma { get; set; }
        public string nombrePrograma { get; set; }
        public Nullable<int> idEstadoCursoPrograma { get; set; }
        public string objetivosPrograma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curso> Cursoes { get; set; }
        public virtual EstadoCursoPrograma EstadoCursoPrograma { get; set; }
    }
}
